image: node:14

pipelines:
  default:
    - step:
        name: Install Dependencies
        caches:
          - node
        script:
          - npm install

  branches:
    main:
      - step:
          name: Build and Test
          caches:
            - node
          script:
            - npm install
            - npm test

      - step:
          name: Deploy to Heroku
          deployment: production
          script:
            - apt-get update && apt-get install -y git
            - git remote add heroku https://github.com/ashishsuffescom/nodejs-demo.git
            - echo "machine api.heroku.com login _ password $HEROKU_API_KEY" > ~/.netrc
            - echo "machine git.heroku.com login _ password $HEROKU_API_KEY" >> ~/.netrc
            - git push heroku main
